### ISSUE TITLE
Update contracts to use pragma ^0.6.0

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#149]
We currently require the 0.5.x compilers.  0.6.x may provide some optimization and convenience benefits, so it may be interesting to try updating the code to `pragma ^0.6.0`.

**Comment by riemann89** [comment]
I've investigated a bit on this: as expected, there are some changes to do on the solidity contracts but nothing particulary crazy. The only annoy thing is that, since the ERC20Mintable contract works for 'pragma ^0.5.0', we have to install 2 versions of the solidity compiler. I suggest to perform these changes once the the new token contract would be available so we can use just one compiler.

**Comment by AntoineRondelet** [comment]
Related to: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2028

**Comment by AntoineRondelet** [comment]
Thread of interest: https://forum.openzeppelin.com/t/where-is-erc20mintable-sol-in-openzeppelin-contracts-3-0/2283

**Comment by AntoineRondelet** [comment]
Switching to 0.6.0 will allow to use the ABIEncoderV2 which is not considered experimental anymore starting v0.6.0. See: https://solidity.readthedocs.io/en/v0.6.0/layout-of-source-files.html#abiencoderv2

**Comment by AntoineRondelet** [comment]
Closing this issue since the solidity code has been ported to solidity 0.8 in #352 which is now merged.
