### ISSUE TITLE
Poposal: Alternative solution to Merkle Tree

### ISSUE THREAD

**Issue by chiro-hiro** [clearmatics/zeth#328]
I'm try to using hash chain instead of Merkle Tree to reduce cost to operate Merkele Tree contract. Here is my proposal https://github.com/chiro-hiro/chainlink please have look.

**Comment by AntoineRondelet** [comment]
Thanks for the ticket @chiro-hiro - unfortunately, this does not seem useful in the context of Zeth because we need to deal with a constant-depth for the Merkle tree in the circuits in order to generate the proof of inclusion (we simply can't deal with an "ever growing" list of hashes here). Hence, the problem is not such much related to adding new leaves to the tree, but rather related to keeping the proofs of inclusion (i.e. verifying Merkle authentication paths) efficient during the zkSNARK proof generation :)
